services:
  - type: web
    name: storyboom-ai-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: HEYGEN_API_KEY
        sync: false
      - key: PICTORY_CLIENT_ID
        sync: false
      - key: PICTORY_CLIENT_SECRET
        sync: false
      - key: PICTORY_USER_ID
        sync: false
      - key: WONDERCRAFT_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: storyboom-ai-db
          property: connectionString

databases:
  - name: storyboom-ai-db
    databaseName: storyboom_ai
    user: storyboom_ai_user
    plan: free 