"""Add sentiment chart data field

Revision ID: 78374a535955
Revises: df1a7d34cf6b
Create Date: 2025-07-16 13:32:25.133818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78374a535955'
down_revision = 'df1a7d34cf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_studies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_chart_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_studies', schema=None) as batch_op:
        batch_op.drop_column('sentiment_chart_data')

    # ### end Alembic commands ###
