"""Add story tracking fields to users table

Revision ID: add_story_tracking_fields
Revises: df1a7d34cf6b
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, Integer, Date


# revision identifiers, used by Alembic.
revision = 'add_story_tracking_fields'
down_revision = 'df1a7d34cf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stories_used_this_month', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('extra_credits', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_reset_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_reset_date')
        batch_op.drop_column('extra_credits')
        batch_op.drop_column('stories_used_this_month')

    # ### end Alembic commands ###
