"""Add subscription fields to users table

Revision ID: add_subscription_fields
Revises: add_story_tracking_fields
Create Date: 2025-01-27 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, Boolean, Date


# revision identifiers, used by Alembic.
revision = 'add_subscription_fields'
down_revision = 'add_story_tracking_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_active_subscription', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('subscription_start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_start_date')
        batch_op.drop_column('has_active_subscription')

    # ### end Alembic commands ###
